### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by eaedk** [AsianZeus/Ooze-Handwritten-Text-Generation#1]
Hi, your work is really interesting, thanks for your sharing.

I have some questions about, please do you have time to answer me ?

About the dataset building you used some transformations techniques for word segmentation, I'll be happy to check the code.

[...]

**Comment by AsianZeus** [comment]
You can use the vertical histogram and horizontal histogram techniques for word and line segmentation respectively.
just apply the binary threshold to the image and segment the area between two words where there are 'n' white columns (considering your background is white).

**Comment by eaedk** [comment]
please could you share code to help me to test that.?

**Comment by AsianZeus** [comment]
Here is the pre-processing code
`
import cv2 as cv
import os
import numpy as np

def countfreq(list):
    white = np.count_nonzero(list)
    return (white, len(list)-white)

def isNotWord(list, threshold):
    size = len(list)
    white, black = countfreq(list)
    ratio = (white/size, black/size)
    # print(white,black,ratio)
    if(ratio[0] > threshold):
        return 1
    else:
        return 0

def rectify(list, pixelThreshold):
    for i in range(pixelThreshold, len(list)-pixelThreshold, pixelThreshold):
        if(np.count_nonzero(list[i-pixelThreshold:i+pixelThreshold]) < pixelThreshold):
            list[i-pixelThreshold:i+pixelThreshold] = [0]*(pixelThreshold*2)
    return list

def FindingContours(ProcessedLine, SegmentedLine):
    height,width=ProcessedLine.shape
    (components, _) = cv.findContours(
        ProcessedLine, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)
    wordslist = []
    for c in components:
        if cv.contourArea(c) < 70000:
            continue
        currBox = cv.boundingRect(c)  # returns (x, y, w, h)
        (x, y, w, h) = currBox
        currImg = SegmentedLine[y-20:y+h+20, 0:width]
        # if(currImg.shape[1] > 60):
        wordslist.append(currImg)
    wordslist.reverse()
    return wordslist

path=os.getcwd()
filenames= os.listdir('images2')
cnt=1
for name in filenames:
    image= cv.imread(path+'/images2/'+name,cv.IMREAD_GRAYSCALE)
    img = cv.threshold(image, 0, 255, cv.THRESH_BINARY_INV + cv.THRESH_OTSU)[1]
    img = cv.dilate(img, np.ones(3))
    img = 255-img
    img = cv.medianBlur(img, 3)
    img = 255-img
    img = cv.dilate(img, np.ones(3))
    img = 255-img

    height,width=img.shape
    wordornot = []

    for i in range(height):
        wordornot.append(isNotWord(img[i], threshold=0.96))

    wordornot = rectify(wordornot, pixelThreshold=10)

    for i in range(height):
        if(wordornot[i] == True):
            img[i] = [0]*width

    cv.namedWindow('dd',0)
    cv.imshow('dd',img)
    cv.waitKey(0)

    imx=FindingContours(img,image)
    linecnt=1
    linesub=97
    for imo in imx:
        try:
            cv.namedWindow('ddx',0)
            cv.imshow('ddx',imo)
            cv.waitKey(0)
            # cv.imwrite(f"Lines3/{name[:-4]}_line_{chr(linesub)}_{linecnt}.png",imo)
            linecnt+=1
            if((linecnt+1)%2==0):
                linesub+=1
                linecnt=1
        except:
            pass
    cnt+=1

# Crop Extra Spaces
path=os.getcwd()
filenames= os.listdir('process')
cnt=1
for name in filenames:
    img = cv.imread(path+'/process/'+name,cv.IMREAD_GRAYSCALE)
    gray = 255*(img < 128).astype(np.uint8) # To invert the text to white
    coords = cv.findNonZero(gray) # Find all non-zero points (text)
    x, y, w, h = cv.boundingRect(coords) # Find minimum spanning bounding box
    rect = img[y-5:y+h+5, x:x+w] # Crop the image - note we do this on the original image
    try:
        if(rect.shape[0]>40):
            cv.imwrite(f'TrainA/{name}', rect) # Save the image
        else:
            cv.imwrite(f'TrainB/{name}', img)
            # print(name)
    except:
        print(name)
`

**Comment by AsianZeus** [comment]
Here is the code for preprocessing:

```
import cv2 as cv
import os
import numpy as np

def countfreq(list):
    white = np.count_nonzero(list)
    return (white, len(list)-white)

def isNotWord(list, threshold):
    size = len(list)
    white, black = countfreq(list)
    ratio = (white/size, black/size)
    # print(white,black,ratio)
    if(ratio[0] > threshold):
        return 1
    else:
        return 0

def rectify(list, pixelThreshold):
    for i in range(pixelThreshold, len(list)-pixelThreshold, pixelThreshold):
        if(np.count_nonzero(list[i-pixelThreshold:i+pixelThreshold]) < pixelThreshold):
            list[i-pixelThreshold:i+pixelThreshold] = [0]*(pixelThreshold*2)
    return list

def FindingContours(ProcessedLine, SegmentedLine):
    height,width=ProcessedLine.shape
    (components, _) = cv.findContours(
        ProcessedLine, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)
    wordslist = []
    for c in components:
        if cv.contourArea(c) < 70000:
            continue
        currBox = cv.boundingRect(c)  # returns (x, y, w, h)
        (x, y, w, h) = currBox
        currImg = SegmentedLine[y-20:y+h+20, 0:width]
        # if(currImg.shape[1] > 60):
        wordslist.append(currImg)
    wordslist.reverse()
    return wordslist

path=os.getcwd()
filenames= os.listdir('images2')
cnt=1
for name in filenames:
    image= cv.imread(path+'/images2/'+name,cv.IMREAD_GRAYSCALE)
    img = cv.threshold(image, 0, 255, cv.THRESH_BINARY_INV + cv.THRESH_OTSU)[1]
    img = cv.dilate(img, np.ones(3))
    img = 255-img
    img = cv.medianBlur(img, 3)
    img = 255-img
    img = cv.dilate(img, np.ones(3))
    img = 255-img

    height,width=img.shape
    wordornot = []

    for i in range(height):
        wordornot.append(isNotWord(img[i], threshold=0.96))

    wordornot = rectify(wordornot, pixelThreshold=10)

    for i in range(height):
        if(wordornot[i] == True):
            img[i] = [0]*width

    cv.namedWindow('dd',0)
    cv.imshow('dd',img)
    cv.waitKey(0)

    imx=FindingContours(img,image)
    linecnt=1
    linesub=97
    for imo in imx:
        try:
            cv.namedWindow('ddx',0)
            cv.imshow('ddx',imo)
            cv.waitKey(0)
            # cv.imwrite(f"Lines3/{name[:-4]}_line_{chr(linesub)}_{linecnt}.png",imo)
            linecnt+=1
            if((linecnt+1)%2==0):
                linesub+=1
                linecnt=1
        except:
            pass
    cnt+=1


# Crop Extra Spaces
path=os.getcwd()
filenames= os.listdir('process')
cnt=1
for name in filenames:
    img = cv.imread(path+'/process/'+name,cv.IMREAD_GRAYSCALE)
    gray = 255*(img < 128).astype(np.uint8) # To invert the text to white
    coords = cv.findNonZero(gray) # Find all non-zero points (text)
    x, y, w, h = cv.boundingRect(coords) # Find minimum spanning bounding box
    rect = img[y-5:y+h+5, x:x+w] # Crop the image - note we do this on the original image
    try:
        if(rect.shape[0]>40):
            cv.imwrite(f'TrainA/{name}', rect) # Save the image
        else:
            cv.imwrite(f'TrainB/{name}', img)
            # print(name)
    except:
        print(name)
```

**Comment by eaedk** [comment]
hey, thanks.

**Comment by AsianZeus** [comment]
Welcome
